### ISSUE TITLE
Uri, access key and secret key

### ISSUE THREAD

**Issue by iberodev** [vsouza/docker-SQS-local#13]
I cannot find any information on how to use this sqs local container.
For instance I am using a c# wrapper library called MassTransit that supports Amazon SQS and in order to configure it I need to provide a server uri, an access key and a secret key.

Since this docker image is not really in AWS, how do I configure those 3 parameters so that I can connect my driver to it?

**Comment by vsouza** [comment]
Hi @iberodev usually AWS Wrappers have an `endpoint_url` option in the `Connection` object.
Check this example using boto: [https://stackoverflow.com/a/32260680](https://stackoverflow.com/a/32260680)
