### ISSUE TITLE
Missing AMD64 architecture Docker image

### ISSUE THREAD

**Issue by FourSigma** [vsouza/docker-SQS-local#17]
Hi, 

Wanted to bring to you attention that your latest release of `sql-local` is missing `amd64` architecture images.  It currently only has `arm64` Docker images. Was this intentional?

https://hub.docker.com/r/vsouza/sqs-local/tags

**Comment by vsouza** [comment]
Hi @FourSigma. I never tested `amd64`, because it wasn't a need for my purpose. Do you tested build with `amd64` architecture?

**Comment by vsouza** [comment]
Closed due inactivity
