### ISSUE TITLE
The container freeze if you run under an `i386` arch

### ISSUE THREAD

**Issue by germanolleunlp** [vsouza/docker-SQS-local#18]
The container freeze if you run under an `i386` arch

<img width="1257" alt="Screen Shot 2024-03-20 at 17 56 18" src="https://github.com/vsouza/docker-SQS-local/assets/5367000/1478b73e-8d0a-4eb3-8487-75eaf70e433a">

**Comment by vsouza** [comment]
@germanolleunlp are you tried to set the env var for OpenJDK?

**Comment by vsouza** [comment]
Closed due inactivity
