### ISSUE TITLE
How to get {{docker_ip}} address please ?

### ISSUE THREAD

**Issue by narlas01** [vsouza/docker-SQS-local#6]

**Comment by narlas01** [comment]
I am using MAC and I tried to give http://localhost:9324/ and 
as I read from some of the posts, I tried to get IP address from "docker inspect ddc7c482135c" command , so I tried 172.17.0.2:9324  but none of these working. I am new to this. Appreciate your answer.

**Comment by vsouza** [comment]
@narlas01 try this: 
`docker-machine start` and `docker-machine ip`
