### ISSUE TITLE
AWS Credentials

### ISSUE THREAD

**Issue by rehpotsirhc** [vsouza/docker-SQS-local#8]
I'm trying to use your local SQS, but when I try and send or receive messages using the AWS .NET SDK it complains of not having credentials. If I supply fake credentials it still complains.

**Comment by vsouza** [comment]
@rehpotsirhc you should configure your credentials in the SDK. This project doesn't have any control with credentials.

Maybe this link can help you:
https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-creds.html
