### ISSUE TITLE
List queues / management interface

### ISSUE THREAD

**Issue by calebickler** [vsouza/docker-SQS-local#9]
Hello,

I am looking at using docker-SQS-local for local development, I was originally going to use RabbitMQ but if I can run SQS local then I don't need to maintain two queue interfaces :)

One thing that I would want when doing local development is some way to list my queues and see the queued messages and consume rates. This way we can see if a queue is getting written to but not consumed.

I tried looking for something in the elasticmq repo but I couldn't find anything. I know there is no UI but is there a command I could `docker exec` to list the queues.

Thanks for this project and your help!

**Comment by vsouza** [comment]
@calebickler try this project, maybe can help you.

https://github.com/aaronshaf/sqs-admin

**Comment by calebickler** [comment]
This worked great.

Here is a docker image I found for it: https://github.com/wheniwork/sqs-admin and here is what my docker-compose looks like now:

~~~~
  sqslocal:
    image: vsouza/sqs-local
    ports:
      - "9324:9324"
  sqsadmin:
    image: wheniwork/sqs-admin
    environment:
      - SQS_ENDPOINT=http://docker.for.win.localhost:9324
    ports:
      - "9325:8002"
~~~~

I now have a local sqs and a management UI.

Thanks!!

**Comment by elliotlings** [comment]
@calebickler do you have any ideas why sqsadmin is returning the following?

```
Error: connect ECONNREFUSED 172.18.0.2:80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```

**Comment by calebickler** [comment]
Hi @elliotlings 
If you are having issues with sqs admin I would make a ticket in the sqs admin repo.

My guess is the `SQS_ENDPOINT` you have configured is not correct.

**Comment by gnuson** [comment]
I had the same issue. The problem was that I was using "- SQS_ENDPOINT=http://localhost:9324" instead of "- SQS_ENDPOINT=http://docker.for.win.localhost:9324"
